WITH_TRA ~wl_houserules/lang/%LANGUAGE%/wl_ranger_tweaks.tra~ BEGIN

//prevent ranger kits from falling and allow them to be evil
COPY_EXISTING ~kitlist.2da~ ~override~ 
	COUNT_2DA_ROWS 9 numrows
	FOR (row = 3; row < numrows; ++row) BEGIN
		READ_2DA_ENTRY row 1 9 name
		READ_2DA_ENTRY row 8 9 class
		PATCH_IF (class = 12)  BEGIN //ranger kits
			INNER_ACTION BEGIN 
				APPEND ~fallen.2da~ ~%name%	0~
			END
			INNER_ACTION BEGIN
				COPY_EXISTING ~alignmnt.2da~ ~override~
					READ_2DA_ENTRIES_NOW numrows2 10
					FOR (row2 = 1; row2 < numrows2; ++row2) BEGIN
						READ_2DA_ENTRY_FORMER numrows2 row2 0 name2
						PATCH_IF (~%name2%~ STRING_EQUAL_CASE ~%name%~) BEGIN
							SET patch_row = %row2%
						END
					END
					SET_2DA_ENTRY %patch_row% 1 10 1
					SET_2DA_ENTRY %patch_row% 2 10 1
					SET_2DA_ENTRY %patch_row% 3 10 1
					SET_2DA_ENTRY %patch_row% 4 10 1
					SET_2DA_ENTRY %patch_row% 5 10 1
					SET_2DA_ENTRY %patch_row% 6 10 1
					SET_2DA_ENTRY %patch_row% 7 10 1
					SET_2DA_ENTRY %patch_row% 8 10 1
					SET_2DA_ENTRY %patch_row% 9 10 1
				BUT_ONLY
			END
		END
		PATCH_IF (class = 18)  BEGIN //multiclass kits
			INNER_ACTION BEGIN
				APPEND ~fallen.2da~ ~%name%	0~
			END
			INNER_ACTION BEGIN
				COPY_EXISTING ~alignmnt.2da~ ~override~
					READ_2DA_ENTRIES_NOW numrows2 10
					FOR (row2 = 1; row2 < numrows2; ++row2) BEGIN
						READ_2DA_ENTRY_FORMER numrows2 row2 0 name2
						PATCH_IF (~%name2%~ STRING_EQUAL_CASE ~%name%~) BEGIN
							SET patch_row = %row2%
						END
					END
					SET_2DA_ENTRY %patch_row% 1 10 1
					SET_2DA_ENTRY %patch_row% 2 10 1
					SET_2DA_ENTRY %patch_row% 3 10 1
					SET_2DA_ENTRY %patch_row% 4 10 1
					SET_2DA_ENTRY %patch_row% 5 10 1
					SET_2DA_ENTRY %patch_row% 6 10 1
					SET_2DA_ENTRY %patch_row% 7 10 1
					SET_2DA_ENTRY %patch_row% 8 10 1
					SET_2DA_ENTRY %patch_row% 9 10 1
				BUT_ONLY
			END
		END
	END
	BUT_ONLY

// prevent ranger true and multi class from falling and allow them to be evil and update class descriptions
COPY_EXISTING ~clastext.2da~ ~override~ 
	COUNT_2DA_ROWS 9 rows
	FOR (row = 1; row < rows; ++row) BEGIN
		READ_2DA_ENTRY row 0 9 name
		READ_2DA_ENTRY row 4 9 string
		PATCH_IF (~%name%~ STRING_EQUAL_CASE ~RANGER~)  BEGIN
			INNER_ACTION BEGIN
				APPEND ~fallen.2da~ ~%name%	0~
			END
			INNER_ACTION BEGIN
				COPY_EXISTING ~alignmnt.2da~ ~override~
					READ_2DA_ENTRIES_NOW numrows2 10
					FOR (row2 = 1; row2 < numrows2; ++row2) BEGIN
						READ_2DA_ENTRY_FORMER numrows2 row2 0 name2
						PATCH_IF (~%name2%~ STRING_EQUAL_CASE ~RANGER~) BEGIN
							SET patch_row = %row2%
						END
					END
					SET_2DA_ENTRY %patch_row% 1 10 1
					SET_2DA_ENTRY %patch_row% 2 10 1
					SET_2DA_ENTRY %patch_row% 3 10 1
					SET_2DA_ENTRY %patch_row% 4 10 1
					SET_2DA_ENTRY %patch_row% 5 10 1
					SET_2DA_ENTRY %patch_row% 6 10 1
					SET_2DA_ENTRY %patch_row% 7 10 1
					SET_2DA_ENTRY %patch_row% 8 10 1
					SET_2DA_ENTRY %patch_row% 9 10 1
				BUT_ONLY
			END
		END
		PATCH_IF (~%name%~ STRING_EQUAL_CASE ~CLERIC_RANGER~)  BEGIN
			INNER_ACTION BEGIN
				APPEND ~fallen.2da~ ~%name%	0~
			END
			INNER_ACTION BEGIN
				COPY_EXISTING ~alignmnt.2da~ ~override~
					READ_2DA_ENTRIES_NOW numrows2 10
					FOR (row2 = 1; row2 < numrows2; ++row2) BEGIN
						READ_2DA_ENTRY_FORMER numrows2 row2 0 name2
						PATCH_IF (~%name2%~ STRING_EQUAL_CASE ~CLERIC_RANGER~) BEGIN
							SET patch_row = %row2%
						END
					END
					SET_2DA_ENTRY %patch_row% 1 10 1
					SET_2DA_ENTRY %patch_row% 2 10 1
					SET_2DA_ENTRY %patch_row% 3 10 1
					SET_2DA_ENTRY %patch_row% 4 10 1
					SET_2DA_ENTRY %patch_row% 5 10 1
					SET_2DA_ENTRY %patch_row% 6 10 1
					SET_2DA_ENTRY %patch_row% 7 10 1
					SET_2DA_ENTRY %patch_row% 8 10 1
					SET_2DA_ENTRY %patch_row% 9 10 1
				BUT_ONLY
			END
		END
		PATCH_IF (~%name%~ STRING_EQUAL_CASE ~RANGER~) BEGIN
			SPRINT find @1
			SPRINT patch_string ~%string%~
			GET_STRREF ~%string%~ desc
			INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
				REPLACE_TEXTUALLY ~%find%~ ~~
			END
		END
	END
	REPLACE ~%patch_string%~ ~%new_desc%~
BUT_ONLY

END