COPY_EXISTING_REGEXP GLOB ~^.+\.itm~ ~override~
	READ_SHORT 0x1c cat
	READ_ASCII 0x22 anim (2) NULL
		PATCH_IF (cat = 2) BEGIN
			LPF DELETE_EFFECT
				INT_VAR
					check_globals = 1
					match_opcode = 144
					match_parameter2 = 1
			END
			LPF DELETE_EFFECT
				INT_VAR
					check_globals = 1
					match_opcode = 145
			END
		END
		PATCH_IF (~%anim%~ STRING_EQUAL ~2A~) BEGIN
			LPF ADD_ITEM_EQEFFECT
				INT_VAR
					opcode = 189
					target = 1
					timing = 2
					parameter1 = "-1"
					parameter2 = 0
			END
		END
		PATCH_IF (~%anim%~ STRING_EQUAL ~3A~) BEGIN
			LPF ADD_ITEM_EQEFFECT
				INT_VAR
					opcode = 189
					target = 1
					timing = 2
					parameter1 = "-2"
					parameter2 = 0
			END
			LPF ADD_ITEM_EQEFFECT
				INT_VAR
					opcode = 92
					target = 1
					timing = 2
					parameter1 = 75
					parameter2 = 2
			END
		END
		PATCH_IF (~%anim%~ STRING_EQUAL ~4A~) BEGIN
			LPF ADD_ITEM_EQEFFECT
				INT_VAR
					opcode = 189
					target = 1
					timing = 2
					parameter1 = "-3"
					parameter2 = 0
			END
			LPF ADD_ITEM_EQEFFECT
				INT_VAR
					opcode = 92
					target = 1
					timing = 2
					parameter1 = 50
					parameter2 = 2
			END
		END
BUT_ONLY