WITH_TRA ~wl_houserules/lang/%LANGUAGE%/wl_item_tweaks.tra~ BEGIN 

COPY_EXISTING_REGEXP GLOB ~^.+\.itm~ ~override~ 
SPRINT missile @8
SPRINT piercing @9
SPRINT crushing @10
SPRINT slashing @11
	PATCH_IF (%SOURCE_SIZE% > 0x70) BEGIN
		READ_SHORT 0x1c cat
			PATCH_IF 
				(cat = 5) OR
				(cat = 4) OR
				(cat = 31) OR
				(cat = 24) BEGIN
					LPF ALTER_ITEM_HEADER
						INT_VAR damage_type = 1
					END
					FOR (index = 0x54 ; index >= 0x50 ; index -= 4) BEGIN // loop through descriptions
						READ_LONG "%index%" "valid"
						PATCH_IF ("%valid%" < 2147483646) AND ("%valid%" >= 0) BEGIN // verify description is valid
							READ_STRREF "%index%" "description"
								PATCH_IF (~%description%~ STRING_CONTAINS_REGEXP ~%missile%~) = 0 BEGIN // more validation
									INNER_PATCH_SAVE new_desc ~%description%~ BEGIN
										REPLACE_TEXTUALLY ~%missile%~ ~%piercing%~
									END
								SAY_EVALUATED "%index%" ~%new_desc%~
								END
						END
					END
				END
			PATCH_IF 
				(cat = 14) BEGIN
					LPF ALTER_ITEM_HEADER
						INT_VAR damage_type = 2
					END
					FOR (index = 0x54 ; index >= 0x50 ; index -= 4) BEGIN // loop through descriptions
						READ_LONG "%index%" "valid"
						PATCH_IF ("%valid%" < 2147483646) AND ("%valid%" >= 0) BEGIN // verify description is valid
							READ_STRREF "%index%" "description"
								PATCH_IF (~%description%~ STRING_CONTAINS_REGEXP ~%missile%~) = 0 BEGIN // more validation
									INNER_PATCH_SAVE new_desc ~%description%~ BEGIN
										REPLACE_TEXTUALLY ~%missile%~ ~%crushing%~
									END
								SAY_EVALUATED "%index%" ~%new_desc%~
								END
						END
					END
				END
			PATCH_IF
				(cat = 25) BEGIN
					READ_LONG 0x64 aboff
					READ_SHORT 0x68 abnum
//					FOR (i=0; i<abnum; i=i+1) BEGIN
					WHILE (abnum > 0) BEGIN
						READ_BYTE (aboff + (abnum - 1) * 0x38) abtyp
						PATCH_IF (abtyp = 2) BEGIN
							WRITE_SHORT (aboff + (abnum - 1) * 0x38 + 0x1c) 3
						END
						SET abnum = (abnum - 1)
					END
					FOR (index = 0x54 ; index >= 0x50 ; index -= 4) BEGIN // loop through descriptions
						READ_LONG "%index%" "valid"
						PATCH_IF ("%valid%" < 2147483646) AND ("%valid%" >= 0) BEGIN // verify description is valid
							READ_STRREF "%index%" "description"
								PATCH_IF (~%description%~ STRING_CONTAINS_REGEXP ~%missile%~) = 0 BEGIN // more validation
									INNER_PATCH_SAVE new_desc ~%description%~ BEGIN
										REPLACE_TEXTUALLY ~%missile%~ ~%slashing%~
									END
								SAY_EVALUATED "%index%" ~%new_desc%~
								END
						END
					END
				END
			PATCH_IF
				(cat = 16) BEGIN
					READ_LONG 0x64 aboff
					READ_SHORT 0x68 abnum
//					FOR (i=0; i<abnum; i=i+1) BEGIN
					WHILE (abnum > 0) BEGIN
						READ_BYTE (aboff + (abnum - 1) * 0x38) abtyp
						PATCH_IF (abtyp = 2) BEGIN
							WRITE_SHORT (aboff + (abnum - 1) * 0x38 + 0x1c) 1
						END
						SET abnum = (abnum - 1)
					END
					FOR (index = 0x54 ; index >= 0x50 ; index -= 4) BEGIN // loop through descriptions
						READ_LONG "%index%" "valid"
						PATCH_IF ("%valid%" < 2147483646) AND ("%valid%" >= 0) BEGIN // verify description is valid
							READ_STRREF "%index%" "description"
								PATCH_IF (~%description%~ STRING_CONTAINS_REGEXP ~%missile%~) = 0 BEGIN // more validation
									INNER_PATCH_SAVE new_desc ~%description%~ BEGIN
										REPLACE_TEXTUALLY ~%missile%~ ~%piercing%~
									END
								SAY_EVALUATED "%index%" ~%new_desc%~
								END
						END
					END
				END
			PATCH_IF
				(cat = 21) BEGIN
					READ_LONG 0x64 aboff
					READ_SHORT 0x68 abnum
//					FOR (i=0; i<abnum; i=i+1) BEGIN
					WHILE (abnum > 0) BEGIN
						READ_BYTE (aboff + (abnum - 1) * 0x38) abtyp
						PATCH_IF (abtyp = 2) BEGIN
							WRITE_SHORT (aboff + (abnum - 1) * 0x38 + 0x1c) 2
						END
						SET abnum = (abnum - 1)
					END
					FOR (index = 0x54 ; index >= 0x50 ; index -= 4) BEGIN // loop through descriptions
						READ_LONG "%index%" "valid"
						PATCH_IF ("%valid%" < 2147483646) AND ("%valid%" >= 0) BEGIN // verify description is valid
							READ_STRREF "%index%" "description"
								PATCH_IF (~%description%~ STRING_CONTAINS_REGEXP ~%missile%~) = 0 BEGIN // more validation
									INNER_PATCH_SAVE new_desc ~%description%~ BEGIN
										REPLACE_TEXTUALLY ~%missile%~ ~%crushing%~
									END
								SAY_EVALUATED "%index%" ~%new_desc%~
								END
						END
					END
				END
	END
BUT_ONLY

END