WITH_TRA ~wl_houserules/lang/%LANGUAGE%/wl_grey_guard.tra~ BEGIN

INCLUDE ~wl_houserules/lib/a7#add_kit_ex.tpa~

LAF ADD_KIT_EX
	INT_VAR
		kit_class		= 6
		mixed 			= RESOLVE_STR_REF (@1)
		help			= RESOLVE_STR_REF (@2)
		
	STR_VAR
		kit_name		= ~wlmkgg~
		clab_path		= ~wl_houserules/components/new_kits/grey_guard/2da/wlmkgg.2da~
		alignmnt		= ~1 1 0 0 0 0 0 0 0~
		backstab		= ~1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4~
		sneakatt		= ~1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 6~
		crippstr		= ~0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4~
		fallen			= 0
		abclasrq		= ~12 0 9 0 13 12~
		abclsmod		= ~0 0 0 0 0 -4~
	RET
		kit_id
END

APPEND ~FALLEN.2DA~ ~wlmkgg 0~

COPY ~wl_houserules/components/new_kits/grey_guard/spl/wlmkgg01.SPL~ ~override~
COPY_EXISTING ~SPWI405.spl~ ~override/wlmkgg02.spl~
	WRITE_SHORT 0x1c 4
	LPF ALTER_SPELL_HEADER
		INT_VAR
			location = 4
	END
			
COPY_EXISTING ~clabpa01.2da~ ~override/wlmkgg.2da~
	APPEND ~wlmkgg.2da~ ~WL_MKGG     AP_WLMKGG01 ****        ****        ****        GA_WLMKGG02 ****        ****        ****        ****         GA_WLMKGG02 ****        ****        ****        ****        GA_WLMKGG02 ****        ****        ****        ****        ****        ****      ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****~

END