WITH_TRA ~wl_houserules/lang/%LANGUAGE%/wl_monk_tweaks.tra~ BEGIN

// replace find traps with detect illusion, give 20 skill points at level 1 for all monks

COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS 10 rows1
	FOR (row1 = 1; row1 < rows1; ++row1) BEGIN
		READ_2DA_ENTRY row1 1 10 name1
		READ_2DA_ENTRY row1 4 10 string1
		READ_2DA_ENTRY row1 5 10 clab
		READ_2DA_ENTRY row1 8 10 class
		PATCH_IF (class = 20) BEGIN
			INNER_ACTION BEGIN // add 20 skill points at level 1 to all monks
				COPY_EXISTING ~thiefskl.2da~ ~override~
					COUNT_2DA_ROWS 3 IA1_rows
					FOR (IA1_row = 0 ; IA1_row < IA1_rows ; IA1_row += 1) BEGIN
						READ_2DA_ENTRY IA1_row 0 3 IA1_name
							PATCH_IF (~%IA1_name%~ STRING_EQUAL_CASE ~MONK~) BEGIN
								SET_2DA_ENTRY %IA1_row% 1 3 20
							END
							PATCH_IF (~%IA1_name%~ STRING_EQUAL_CASE ~%name1%~) BEGIN
								SET_2DA_ENTRY %IA1_row% 1 3 20
							END
					END
			END
			INNER_ACTION BEGIN // replace find traps with detect illusion for all monks
				COPY_EXISTING ~thiefscl.2da~ ~override~
					COUNT_2DA_COLS IA2_cols
					SET IA2_cols1 = (%IA2_cols% - 1)
					COUNT_2DA_ROWS %IA2_cols% IA2_rows
					FOR (IA2_row = 0 ; IA2_row < IA2_rows ; IA2_row += 1) BEGIN
						READ_2DA_ENTRY IA2_row 0 IA2_cols1 IA2_skill
							PATCH_IF (~%IA2_skill%~ STRING_EQUAL_CASE ~FIND_TRAPS~) BEGIN
								SET IA2_patch_row1 = %IA2_row%
							END
							PATCH_IF (~%IA2_skill%~ STRING_EQUAL_CASE ~DETECT_ILLUSION~) BEGIN
								SET IA2_patch_row2 = %IA2_row%
							END
					END
					FOR (IA2_col = 1 ; IA2_col < IA2_cols1 ; ++IA2_col) BEGIN
						READ_2DA_ENTRY 0 IA2_col IA2_cols1 IA2_name
						PATCH_IF (~%IA2_name%~ STRING_EQUAL_CASE ~MONK~) BEGIN
							SET IA2_col1 = (%IA2_col% + 1)
							SET_2DA_ENTRY %IA2_patch_row1% IA2_col1 IA2_cols1 0
							SET_2DA_ENTRY %IA2_patch_row2% IA2_col1 IA2_cols1 100
						END
						PATCH_IF (~%IA2_name%~ STRING_EQUAL_CASE ~%name1%~) BEGIN
							SET IA2_col1 = (%IA2_col% + 1)
							SET_2DA_ENTRY %IA2_patch_row1% IA2_col1 IA2_cols1 0
							SET_2DA_ENTRY %IA2_patch_row2% IA2_col1 IA2_cols1 100
						END
					END 
			END
		END
		PATCH_IF (~%name1%~ STRING_EQUAL_CASE ~DARK_MOON~) BEGIN // remove redundant line from darkmoon description
			SPRINT findDM1 @8
			SPRINT patch_string ~%string1%~
			GET_STRREF ~%string1%~ desc
			INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
				REPLACE_TEXTUALLY ~%findDM1%~ ~~ 
			END
		END
	END
	REPLACE ~%patch_string%~ ~%new_desc%~
BUT_ONLY

COPY_EXISTING ~clastext.2da~ ~override~ //update kit description in clastext
	COUNT_2DA_ROWS 9 rows
	FOR (row = 0 ; row < rows ; row += 1) BEGIN
		READ_2DA_ENTRY row 0 9 name3
		READ_2DA_ENTRY row 4 9 string3
		PATCH_IF (~%name3%~ STRING_EQUAL_CASE ~DARK_MOON~) BEGIN
			SPRINT find1 @8
			SPRINT patch_string ~%string3%~
			GET_STRREF ~%string3%~ desc
			INNER_PATCH_SAVE new_desc ~%desc%~ BEGIN
				REPLACE_TEXTUALLY ~%find1%~ ~~
			END
		END
	END
	REPLACE ~%patch_string%~ ~%new_desc%~
BUT_ONLY

END